Repository wagtail/wagtail-wordpress-import, pull requests merged in 2022-01, with the labels that each got.

#129 Support slash in file path in reduce command
  wagtail_wordpress_import/management/commands/reduce_xml.py
  wagtail_wordpress_import/test/tests/test_commands.py
Labels: bug, enhancement

#127 PyPi link and docs
  docs/long_description.md
  setup.py
Labels: documentation

#126 update README for issues raised
  README.md
Labels: documentation

#125 Issue/fatal error requests
  wagtail_wordpress_import/block_builder_defaults.py
  wagtail_wordpress_import/test/tests/test_block_builder.py
Labels: bug
